# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: text/html

###

POST http://127.0.0.1:8000/chat
Accept: application/json
Content-Type: multipart/form-data; boundary=RecipeFinderBoundary

--RecipeFinderBoundary
Content-Disposition: form-data; name="wiadomosc"

Mam jajka, pomidory i ser. Co mogę zrobić?
--RecipeFinderBoundary--

###
